<a href="https://colab.research.google.com/github/cdevrywhr/pythonbootcamp/blob/main/7_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Python (Numpy)

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.random.random(5)

array([0.07735832, 0.3953866 , 0.57511649, 0.70233192, 0.4442673 ])

In [8]:
# 1D array
new_arr = np.array([1,2,3])

In [10]:
new_ones = np.ones(3)

In [11]:
new_arr+new_ones

array([2., 3., 4.])

In [12]:
new_arr*3

array([3, 6, 9])

In [14]:
new_arr[0]

1

In [15]:
new_arr[1]

2

In [16]:
new_arr[2]

3

In [18]:
new_arr.max()

3

In [19]:
new_arr.min()

1

In [20]:
new_arr.mean()

2.0

In [21]:
new_arr.sum()

6

In [22]:
new_arr.std()

0.816496580927726

In [25]:
#matrix 
x = np.array([[10,20],[30,40]])
x

array([[10, 20],
       [30, 40]])

In [27]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.random.random((4,5))

array([[0.73091075, 0.2074026 , 0.28588898, 0.73387788, 0.71970924],
       [0.03029457, 0.42489888, 0.28097844, 0.31494602, 0.36676741],
       [0.8590201 , 0.35695492, 0.10429016, 0.84903797, 0.70721164],
       [0.21593667, 0.3409064 , 0.85222535, 0.76644863, 0.20345175]])

In [31]:
y = np.array([[2,4],[5,6]])
y

array([[2, 4],
       [5, 6]])

In [32]:
x+y

array([[12, 24],
       [35, 46]])

In [33]:
x.dot(y) 

array([[120, 160],
       [260, 360]])

In [36]:
np.dot(x,y)

array([[120, 160],
       [260, 360]])

In [34]:
y.max()

6

In [35]:
y.min()

2

In [46]:
#indexing
y

array([[2, 4],
       [5, 6]])

In [45]:
y[0,0] #[row,col]

2

In [41]:
y[0,1]

4

In [42]:
y[1,0]

5

In [43]:
y[1,1]

6

In [44]:
y[0:2,1]

array([4, 6])

In [47]:
y[1,0:2]

array([5, 6])

In [ ]:
# reshape(array,shape)

In [53]:
new_data = np.array([1,2,3,4,5,6,7,8])

In [62]:
new_data.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#multideminsional 

In [64]:
x = np.array([[[10,20],[3,40]], [[50,60],[70,80]]])
x

array([[[10, 20],
        [ 3, 40]],

       [[50, 60],
        [70, 80]]])

In [67]:
np.ones((5,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
np.zeros((4,5,1))

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.]]])

In [75]:
v = np.array([1,2,3,4,5], dtype=complex)
v

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [73]:
listx = x.tolist()
listx

[[[10, 20], [3, 40]], [[50, 60], [70, 80]]]